### ISSUE TITLE
Instruction operand is null

### ISSUE THREAD

**Issue by ghost** [mobile46/DotNetUniversalPatcher#8]
Hello, I have tried to empty few method bodys. But I'm getting same error always. How I can fix it?
![image](https://user-images.githubusercontent.com/74210601/196821634-fc7501d0-5512-4d22-90b8-5f011b2b34c5.png)

**Comment by mobile46** [comment]
Hello, obfuscated targets are not supported fully by dnup for now. Try deobfuscate it properly.
